import ragul from './ragul.jpeg';
import abar from './abar.jpg';
import nalini from './nalini.jpeg';
import mani from './mani.jpeg';
import kani from './kani.jpeg';
import laks from './laks.jpeg';
import nik from './nik.jpeg';
import kums from './kums.jpeg';
import rashi from './rashi.jpeg';
import profile from './download.png'
import aparnarani from './aparnarani.jpeg';
import farhan from './farhan.jpg';
import hari from './hari.jpeg'
import sreejumam from './sreejumam.jpeg'
import shagana from './shagana.jpeg'
import prithu from './prithu.jpg'
import deepak from './deepak.jpg'
import suji from './suji.jpeg'
import kirubashini from './kirubashini.jpeg'
import praveena from './praveena.jpeg'
import kavya from './kavya.jpg'
import nagul from './nagul.jpg'
import nandy from './nandy.jpeg'
export { ragul, abar, nalini , mani,   profile , kani, laks , nik, kums , rashi, aparnarani, farhan, deepak, hari ,sreejumam , shagana, prithu , suji , kirubashini ,praveena , kavya, nagul , nandy}